<a href="https://colab.research.google.com/github/vasumaha/aarogya/blob/master/mercredes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install feature-engine

Requirement already satisfied: feature-engine in /usr/local/lib/python3.6/dist-packages (1.0.2)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from feature-engine) (1.4.1)
Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.6/dist-packages (from feature-engine) (1.19.5)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.6/dist-packages (from feature-engine) (0.22.2.post1)
Requirement already satisfied: statsmodels>=0.11.1 in /usr/local/lib/python3.6/dist-packages (from feature-engine) (0.12.2)
Requirement already satisfied: pandas>=1.0.3 in /usr/local/lib/python3.6/dist-packages (from feature-engine) (1.1.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.22.2->feature-engine) (1.0.0)
Requirement already satisfied: patsy>=0.5 in /usr/local/lib/python3.6/dist-packages (from statsmodels>=0.11.1->feature-engine) (0.5.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=1.0.3->feature-engine) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=1.0.3->feature-engine) (2018.9)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from patsy>=0.5->statsmodels>=0.11.1->feature-engine) (1.15.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("/content/train.csv")
cvdata=pd.read_csv("/content/train.csv")

In [4]:
df.head()

   ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3   9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4  13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0

[5 rows x 378 columns]

In [5]:
#size and variables
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 13.8 MB

In [6]:
df.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

In [7]:
df.isnull().mean().sort_values(ascending=False)

X385    0.0
X132    0.0
X123    0.0
X124    0.0
X125    0.0
       ...
X259    0.0
X260    0.0
X261    0.0
X262    0.0
ID      0.0
Length: 378, dtype: float64

In [8]:
df.describe()

                ID            y  ...         X384         X385
count  4209.000000  4209.000000  ...  4209.000000  4209.000000
mean   4205.960798   100.669318  ...     0.000475     0.001426
std    2437.608688    12.679381  ...     0.021796     0.037734
min       0.000000    72.110000  ...     0.000000     0.000000
25%    2095.000000    90.820000  ...     0.000000     0.000000
50%    4220.000000    99.150000  ...     0.000000     0.000000
75%    6314.000000   109.010000  ...     0.000000     0.000000
max    8417.000000   265.320000  ...     1.000000     1.000000

[8 rows x 370 columns]

In [9]:
df.skew().sort_values(ascending=False)

X207    64.876806
X257    64.876806
X210    64.876806
X339    64.876806
X260    64.876806
          ...
X229    -4.702223
X361    -5.146612
X111    -6.062968
X74    -37.429924
X205   -64.876806
Length: 370, dtype: float64

In [10]:
df.kurt().sort_values(ascending=False)

X257    4209.000000
X33     4209.000000
X207    4209.000000
X339    4209.000000
X210    4209.000000
           ...
X194      -1.980089
X191      -1.987336
X362      -1.994330
X337      -1.996579
X127      -2.000571
Length: 370, dtype: float64

In [11]:
df.nunique()

ID      4209
y       2545
X0        47
X1        27
X2        44
        ...
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 378, dtype: int64

In [12]:
df.describe(include='O')

          X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     w     g     j
freq     360   833  1659  1942  4205   231  1042   277

In [13]:
df.corr()

            ID         y       X10  X11  ...      X382      X383      X384      X385
ID    1.000000 -0.055108  0.001602  NaN  ... -0.038171 -0.009332 -0.015355  0.029059
y    -0.055108  1.000000 -0.026985  NaN  ... -0.159815  0.040291 -0.004591 -0.022280
X10   0.001602 -0.026985  1.000000  NaN  ... -0.010164 -0.004740 -0.002532 -0.004387
X11        NaN       NaN       NaN  NaN  ...       NaN       NaN       NaN       NaN
X12   0.058988  0.089792 -0.033084  NaN  ... -0.024937 -0.011628 -0.006212 -0.010765
...        ...       ...       ...  ...  ...       ...       ...       ...       ...
X380 -0.013577  0.040932 -0.010479  NaN  ... -0.007899 -0.003683 -0.001968 -0.003410
X382 -0.038171 -0.159815 -0.010164  NaN  ...  1.000000 -0.003572 -0.001908 -0.003307
X383 -0.009332  0.040291 -0.004740  NaN  ... -0.003572  1.000000 -0.000890 -0.001542
X384 -0.015355 -0.004591 -0.002532  NaN  ... -0.001908 -0.000890  1.000000 -0.000824
X385  0.029059 -0.022280 -0.004387  NaN  ... -0.003307 -0.001542 -0.000824  1.000000

[370 rows x 370 columns]

In [14]:
X=df.drop(columns=['y', 'ID'])
y=df['y']

cv=cvdata.drop(columns=['ID','y'])

In [15]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
from feature_engine.imputation import MeanMedianImputer
num_imputer = MeanMedianImputer()
num_imputer.fit(X_train)

MeanMedianImputer(imputation_method='median',
                  variables=['X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16',
                             'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23',
                             'X24', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31',
                             'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38',
                             'X39', 'X40', ...])

In [17]:
X_train.head()

      X0  X1  X2 X3 X4  X5 X6  ... X378  X379  X380  X382  X383  X384  X385
1006   m   v  as  c  d  ag  k  ...    0     0     0     0     0     0     0
1840   n   s  as  d  d  ae  g  ...    0     0     0     0     0     0     0
3792   f   c   m  c  d   v  i  ...    0     0     0     0     0     0     0
152    j  aa   g  d  d   i  i  ...    0     0     0     0     0     0     0
1557  ay   i  as  c  d  ad  l  ...    0     0     0     0     0     0     0

[5 rows x 376 columns]

In [18]:
cv.head()

   X0 X1  X2 X3 X4 X5 X6 X8  ...  X377  X378  X379  X380  X382  X383  X384  X385
0   k  v  at  a  d  u  j  o  ...     1     0     0     0     0     0     0     0
1   k  t  av  e  d  y  l  o  ...     0     0     0     0     0     0     0     0
2  az  w   n  c  d  x  j  x  ...     0     0     0     0     1     0     0     0
3  az  t   n  f  d  x  l  e  ...     0     0     0     0     0     0     0     0
4  az  v   n  f  d  h  d  n  ...     0     0     0     0     0     0     0     0

[5 rows x 376 columns]

In [19]:
X_train=num_imputer.transform(X_train)
X_test=num_imputer.transform(X_test)
cv=num_imputer.transform(cv)

In [22]:
from feature_engine.encoding import RareLabelEncoder
rare_encoder = RareLabelEncoder()
rare_encoder.fit(X_train)

X_train=rare_encoder.transform(X_train)
X_test=rare_encoder.transform(X_test)
cv=rare_encoder.transform(cv)

/usr/local/lib/python3.6/dist-packages/feature_engine/encoding/rare_label.py:160: UserWarning: The number of unique categories for variable X3 is less than that indicated in n_categories. Thus, all categories will be considered frequent
  "considered frequent".format(var)
/usr/local/lib/python3.6/dist-packages/feature_engine/encoding/rare_label.py:160: UserWarning: The number of unique categories for variable X4 is less than that indicated in n_categories. Thus, all categories will be considered frequent
  "considered frequent".format(var)

In [25]:

from feature_engine.encoding import OrdinalEncoder
cat_encoder = OrdinalEncoder()

cat_encoder.fit(X_train,y_train)

X_train=cat_encoder.transform(X_train)
X_test=cat_encoder.transform(X_test)
cv=cat_encoder.transform(cv)

In [27]:
from sklearn.feature_selection import VarianceThreshold
varThresh= VarianceThreshold()
varThresh.fit(X_train)

X_train=varThresh.transform(X_train)
X_test=varThresh.transform(X_test)
cv=varThresh.transform(cv)

In [28]:
from sklearn.decomposition import PCA

pca=PCA(n_components=0.95)

pca.fit(X_train)

X_train=pca.transform(X_train)
X_test=pca.transform(X_test)
cv=pca.transform(cv)

In [30]:
from xgboost import XGBRegressor

xgbr=XGBRegressor()

xgbr.fit(X_train,y_train)

[20:05:31] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [32]:
from sklearn.metrics import mean_squared_error
import math

y_test_pred=xgbr.predict(X_test)
rms=math.sqrt(mean_squared_error(y_test,y_test_pred))
rms

8.58540350144538

In [34]:
final_preds=xgbr.predict(cv)
final_preds

array([111.1094  ,  94.65273 ,  84.325905, ..., 112.04348 ,  92.00694 ,
        94.003136], dtype=float32)